### ISSUE TITLE
error: Could Not Find a Valid Seed

### ISSUE THREAD

**Issue by LeoninJesterXII** [RickdeJager/stegseek#13]
I'm trying to use StegSeek to crack the attached image, but it can't find a valid seed, and none of the wordlists I've used can valid passcodes.

Is it possible the image is a different type of steg
![hidden](https://user-images.githubusercontent.com/34839156/163672771-620533e0-ab53-470b-9719-dff221b3c64a.jpg)
?

**Comment by RickdeJager** [comment]
If `--seed` doesn't find a valid seed then the image does not contain steghide content. I've had a peek at this image and I can confirm it's something else.  
Of course I won't spoil anything as this may be an active CTF challenge and random steg challenges are rather off topic for this issue tracker.

gl.

**Comment by LeoninJesterXII** [comment]
Would you be willing to share which tools you used?

I'm very new to Steg, and this is from a scavenger hunt that I was not aware would have this sort of challenge in it. As it is, I'm dead in the water.
