### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by the1rig** [RickdeJager/stegseek#14]
First of all awesome tool! Is arm64 support on the roadmap? It would be awesome to be able to run this on a M1 Mac.

**Comment by RickdeJager** [comment]
While I don't have any plans to ship binaries for other archs, the project should be fine to build on arm64 as well. See https://github.com/RickdeJager/stegseek/blob/master/BUILD.md for the steps. If the dependencies are available for your system, it should be fairly straightforward

**Comment by the1rig** [comment]
Thanks for that! Not sure why I couldn't find those instructions but it worked like a charm :)
