### ISSUE TITLE
Fatal Error: mcrypt.h - no such file or directory

### ISSUE THREAD

**Issue by hazeyez** [RickdeJager/stegseek#15]
(haze㉿kali)-[~/hacking/stegseek/build]
└─$ make          
[  1%] Building CXX object src/CMakeFiles/stegseek_lib.dir/Arg.cc.o
[  2%] Building CXX object src/CMakeFiles/stegseek_lib.dir/Arguments.cc.o
In file included from /home/haze/hacking/stegseek/src/Arguments.cc:31:
/home/haze/hacking/stegseek/src/MCryptPP.h:28:10: fatal error: mcrypt.h: No such file or directory
   28 | #include <mcrypt.h>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/stegseek_lib.dir/build.make:90: src/CMakeFiles/stegseek_lib.dir/Arguments.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:118: src/CMakeFiles/stegseek_lib.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by RickdeJager** [comment]
It seems like you're missing the libmcrypt-dev package.  
  
Have you tried following along with the [build instructions](https://github.com/RickdeJager/stegseek/blob/master/BUILD.md) ? I wrote them based on Ubuntu, so they should transfer pretty well to kali

**Comment by hazeyez** [comment]
> It seems like you're missing the libmcrypt-dev package.
> 
> Have you tried following along with the [build instructions](https://github.com/RickdeJager/stegseek/blob/master/BUILD.md) ? I wrote them based on Ubuntu, so they should transfer pretty well to kali

I found another way but thank you for responding! If I have to install again I will try this!
