### ISSUE TITLE
[PROPOSAL] - StegSeek in BlackArch repository

### ISSUE THREAD

**Issue by D3vil0p3r** [RickdeJager/stegseek#16]
Hello @RickdeJager 
StegSeek is a wonderful tool. Why don't you insert it inside BlackArch repo in order to be retrieved very quickly by `pacman -Syy stegseek`?

If you need support, I can create for you the PKGBUILD to be submitted on BlackArch repo.

Thanks!

**Comment by RickdeJager** [comment]
Glad you enjoy the tool!  
  
I don't currently have any plans to package for other distro's. Except for the occasional bug fix, I consider this project done, and I'd rather spend my time on other projects. "Officially" packaging, testing, and supporting  multiple distro's takes quite some time as well.  

I know there is already a package on Arch's AUR if that helps, but that one is not published by me either.

**Comment by D3vil0p3r** [comment]
> Glad you enjoy the tool!
> 
> I don't currently have any plans to package for other distro's. Except for the occasional bug fix, I consider this project done, and I'd rather spend my time on other projects. "Officially" packaging, testing, and supporting multiple distro's takes quite some time as well.
> 
> I know there is already a package on Arch's AUR if that helps, but that one is not published by me either.

If you agree, I can take care of the BlackArch package of StegSeek. It will be easy to maintain for me because I will set this GitHub repo as source, so, also in case of exceptional bug fix, I can maintain the related BlackArch package with 0 effort.
