### ISSUE TITLE
m1 how to install on a m1 mac running kali?

### ISSUE THREAD

**Issue by pedrouga** [RickdeJager/stegseek#17]
qustion on a m1 mac installation running kali on a vm

**Comment by pedrouga** [comment]
i have tried to install on a m1 mac, but seems that starts to install the amd version and also requires amd libraries. dont know what to do.

thanks

**Comment by RickdeJager** [comment]
I don't ship a binary for arm so you will have to [build stegseek from source](https://github.com/RickdeJager/stegseek/blob/master/BUILD.md).  

Someone else already managed to build for an m1 mac (see issue #14), so it should work just fine.
