### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by torabi12** [RickdeJager/stegseek#21]
I wanted to install the tool on the latest Ubuntu desktop but I got these errors:

![kép](https://github.com/RickdeJager/stegseek/assets/98665813/fd0224ed-3733-457a-b4ca-22b902ba59b6)

Can someone help me how to solve it?

**Comment by RickdeJager** [comment]
Looks like you're missing `libmcrypt-dev`, check the dependencies here: https://github.com/RickdeJager/stegseek/blob/master/BUILD.md#installing-dependencies

On Ubuntu:23.04 the command is still `sudo apt install libmhash-dev libmcrypt-dev libjpeg-dev zlib1g-dev`, I'd expect it to be the same on latest, but some packages might have been renamed or removed.

**Comment by torabi12** [comment]
Thank you, adding the needed dependencies solved the problem:

![kép](https://github.com/RickdeJager/stegseek/assets/98665813/fdb8fce3-6e5f-4512-9deb-4b8899248beb)
