### ISSUE TITLE
custom wordlist issues 

### ISSUE THREAD

**Issue by solanuscasey** [RickdeJager/stegseek#23]
I am currently trying to crack this image, but stegseek could not find a valid seed and rockyou.txt did not have the password. I have an idea of what the password could be, but I do not know the format necessary for a custom word list. 

![steg1](https://github.com/RickdeJager/stegseek/assets/130777143/f3a3eefb-d19d-4dd1-bd30-0f789ec5ea78)

**Comment by RickdeJager** [comment]
If stegseek didn't find a seed, then the image does not contain any data encoded by steghide. A different wordlist will not make a difference.  
 
As for the wordlist format, that's just a file with one password per line.  

Closing as this is not a stegseek issue.

**Comment by solanuscasey** [comment]
do you have any other recommendations for any steg program?

**Comment by HarbingerOfFire** [comment]
I did a little research on the image and It looks like it might have been edited by [Little CMS](https://github.com/mm2/Little-CMS) by the user (though I can't be sure cause I don't know what the online EXIF scanner is viewing). Maybe mess around with the photo in the Little CMS program and see if you can find any of the edits made and reverse them. Maybe then you can find the encoded data. It really depends though on what you're working on.

**Comment by solanuscasey** [comment]
Alright thank you, I have tried more convention photo editing for small shifts but I'll give this a shot.
